config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  scope "/flight-booker" do
    root "flights#index"
    get "flights/index"
    get "/flights" => "flights#index"
    get "bookings/new"
    get "bookings/:booking_id" => "bookings#show", as: :booking
    post "bookings" => "bookings#create"
  end

  # TODO: search and view on same page. Set up your FlightsController and
  # routes to make the Index page (/flights) the root route.
  # Create your search form on the /flights index page to submit
  # using a GET (not POST) request back to the same URL.
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, dependent: :destroy, class_name: "Flight", foreign_key: "departure_airport_id"
  has_many :arriving_flights, dependent: :destroy, class_name: "Flight", foreign_key: "departure_airport_id"

  validates_uniqueness_of :code
  validates_length_of :code, minimum: 3
  validates_length_of :name, minimum: 10
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers, dependent: :destroy
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"
  has_many :bookings, dependent: :destroy
  has_many :passengers, through: :bookings

  attribute :duration, :duration

  def self.find_by_params(params)
    where(departure_airport: params[:departure_airport],
          arrival_airport: params[:arrival_airport])
    .filter { |f| f.start_time.to_date == params[:start_time].to_date }
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
  has_many :flights, through: :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    if params_present?
      @no_of_passengers = bookings_params[:no_of_passengers]
      unless @no_of_passengers.to_i.between?(1, 4)
        flash[:alert] =  "Only till 4 passengers are allowed in a booking."
        redirect_to "/flights/index"
      end
      begin
        flight_id = bookings_params[:flight_id]
        @flight = Flight.find(flight_id)
      rescue ActiveRecord::RecordNotFound
        flash[:alert] =  "Invalid flight??? Try again."
        redirect_to "/flights/index"
      end
      @passengers = []
      @no_of_passengers.to_i.times do
        @passengers << Passenger.new
      end
    else
      flash[:alert] = "Please select a flight!"
      redirect_to "/flights/index"
    end
  end

  def create
    @booking = Booking.build(bookings_params)
    if @booking.save
      flash[:notice] = "Booked!"
      redirect_to booking_path(@booking)
      # this is just for learning how to send email
      PassengerMailer.with(user: @booking.passengers.first).confirmation_mail.deliver_now
    else
      flash[:alert] = "Invalid details. Could not book flight!"
      redirect_to "/flights/index"
    end
  end

  def show
    @booking = Booking.find(params[:booking_id])
    @passengers = @booking.passengers
    @flight = @booking.flight
  end

  def params_present?
    params.has_key?(:booking) &&
    params.dig(:booking, :flight_id) &&
    params.dig(:booking, :no_of_passengers)
  end

  def bookings_params
    params.expect(booking: [ :flight_id, :no_of_passengers,
                             passengers_attributes: [ [ :name, :email ] ]
    ])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    if params_present?
      @flights = Flight.find_by_params(flights_params)
      @no_of_passengers = flights_params[:no_of_passengers]
    end
  end

  private

  def params_present?
    params.has_key?(:flight) &&
    params.dig(:flight, :departure_airport) &&
    params.dig(:flight, :arrival_airport) &&
    params.dig(:flight, :start_time) &&
    params.dig(:flight, :no_of_passengers)
  end

  def flights_params
    params.expect(flight:
                  [ :start_time,
                    :departure_airport,
                    :arrival_airport,
                    :no_of_passengers ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flight_helper.rb
module FlightHelper
  def format_to_date(start_time)
    start_time.to_date.strftime("%a, %d %b %Y")
  end

  def format_to_time(start_time)
    start_time.strftime("%H:%M %Z(%z)")
  end
end

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>

<p>
  Flight no.
  <%= @flight.id %>
  info:
  <div class="flight-details">
    <%= render partial: "flights/info",
    locals: {
      flight_id: @flight.id,
      departure_airport: @flight.departure_airport,
      arrival_airport: @flight.arrival_airport,
      duration: @flight.duration,
      start_time: @flight.start_time,
    } %>
  </div>
</p>

<%= form_with model: Booking.new, data: {controller: 'booking', booking_target: "form", booking_passenger_index_value: @passengers.size - 1 }, method: :post do |form| %>
  <template data-booking-target="template">
    <%= form.fields_for :passengers, Passenger.new, child_index: @passengers.size - 1 do |passenger_field| %>
      <div>
        <br>
        Passenger
        <%= passenger_field.index + 1 %>
        info :
        <br>
        <%= passenger_field.label :name, "Name : " %>
        <%= passenger_field.text_field :name %>
        <%= passenger_field.label :email, "Email : " %>
        <%= passenger_field.text_field :email %>
        <%= content_tag :span,
        "Remove",
        data: {
          action: "click->booking#removePassenger",
          booking_passenger_index_param: passenger_field.index,
        } %>
      </div>
    <% end %>
  </template>

  <%= form.fields_for :passengers, @passengers do |passenger_field| %>
    <div>
      <br>
      Passenger
      <%= passenger_field.index + 1 %>
      info :
      <br>
      <%= passenger_field.label :name, "Name : " %>
      <%= passenger_field.text_field :name %>
      <%= passenger_field.label :email, "Email : " %>
      <%= passenger_field.text_field :email %>
      <%= content_tag :span,
      "Remove",
      data: {
        action: "click->booking#removePassenger",
        booking_passenger_index_param: passenger_field.index,
      } %>
    </div>
  <% end %>

  <div data-booking-target="new">
  </div>

  <p data-action="click->booking#addPassenger">Add Passenger</p>

  <%= form.hidden_field :flight_id, value: @flight.id %>

  <input type="submit" name="commit" value="Book">
<% end %>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>

<%= button_to "Home", :flights_index, method: :get %>
<h2>
  Booking ID:
  <%= @booking.id %>
</h2>
<p>
  Flight no.
  <%= @flight.id %>
  info:
  <div class="flight-details">
    <%= render partial: "flights/info",
    locals: {
      flight_id: @flight.id,
      departure_airport: @flight.departure_airport,
      arrival_airport: @flight.arrival_airport,
      duration: @flight.duration,
      start_time: @flight.start_time,
    } %>
  </div>
</p>

<% @passengers.each_with_index do |passenger, index| %>
  <p>
    Passenger No.
    <%= index + 1 %>
    Info:
  </p>
  <div class="passenger-details">
    <p>
      Name :
      <%= passenger.name %>
    </p>
    <p>
      Email :
      <%= passenger.email %>
    </p>
  </div>
<% end %>

app/views/flights/_info.html.erb
<span>
  <span>
    <%= departure_airport.name %>
    (
    <%= departure_airport.code %>
    )
  </span>
  <span>
    To ==>
  </span>
  <span>
    <%= arrival_airport.name %>
    (
    <%= arrival_airport.code %>
    )
  </span>
</span>
<br>
<span>
  <%= duration.inspect %>
</span>
<br>
<span>
  <%= format_to_date(start_time) %>
  -
  <%= format_to_time(start_time) %>
</span>

app/views/flights/_results.html.erb
<div class="flight-details">
  <%= form.radio_button :flight_id, flight_id %>

  <label for=<%= "booking_flight_id_#{flight_id}" %>>
    <%= render partial: "info",
    locals: {
      flight_id: flight_id,
      departure_airport: departure_airport,
      arrival_airport: arrival_airport,
      duration: duration,
      start_time: start_time,
      form: form,
    } %>
  </label>
</div>

app/views/flights/_search_form.html.erb
<search>
  <%= form_with model: Flight.new , method: :get do |form| %>

    <div>

      <%= form.label :departure_airport, "Departure Airport" %>
      <%= form.collection_select :departure_airport, Airport.all, :id, :name %>

      <%= form.label :arrival_airport, "Arrival Airport:" %>
      <%= form.collection_select :arrival_airport, Airport.all, :id, :name %>

    </div>
    <div>

      <%= form.label :no_of_passengers, "No. of passengers:" %>
      <%= form.select :no_of_passengers, (1..4).to_a %>

    </div>
    <div>

      <%= form.label :start_time, "Date:" %>
      <%= form.collection_select :start_time,
                             Flight
                               .all
                               .select(:start_time)
                               .uniq { |f| f.start_time.to_date },
                             :start_time,
                             lambda { |f| format_to_date(f.start_time) } %>
    </div>
    <%= form.submit "Search" %>
  <% end %>
</search>

app/views/flights/index.html.erb
<h1>Flights</h1>

<%= render "search_form" %>

<% if @flights %>

  <% unless @flights.empty? %>
    <p>
      flights for
      <%= @no_of_passengers %>
      passengers:
    </p>

    <%= form_with model: Booking.new, url: bookings_new_path, method: :get do |form| %>
      <% @flights.each do |flight| %>
        <%= render partial: "results",
        locals: {
          flight_id: flight.id,
          departure_airport: flight.departure_airport,
          arrival_airport: flight.arrival_airport,
          duration: flight.duration,
          start_time: flight.start_time,
          form: form,
        } %>
      <% end %>

      <%= form.hidden_field :no_of_passengers, value: @no_of_passengers %>

      <input type="submit" name="commit" value="Select">
    <% end %>
  <% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Flight Booker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <% if flash %>
      <div>
        <%= flash[:alert] %>
      </div>
    <% end %>
    <% if flash %>
      <div>
        <%= flash[:notice] %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>